baseURL = "https://lorenzodebe.com/"
languageCode = "en-us"
title = "Lorenzo IN3HBB (as3ii)"
theme = "hugograyscale"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Lorenzo's portfolio"
    author = "Lorenzo Debertolis"
